theme: jekyll-theme-slate
title: Jihyeug's homepage
url: 'https://jihyeugjang.github.io'
baseurl: '/'
markdown: kramdown

author:
name: Jihyeug Jang
email: 4242ab@gmail.com
github_username: JihyeugJang
